---
- name: Update Pacman cache
  become: true
  community.general.pacman:
    update_cache: true

- name: Enable grub-btrfsd.service
  become: true
  ansible.builtin.systemd_service:
    name: grub-btrfsd.service
    state: reloaded
    enabled: true
