---
- name: Configure my PC
  hosts: localhost
  vars:
    arch_config_ansible_aur_user: aur_builder
  roles:
    - arch_config
  tasks:
    - name: Enable multilib
      become: true
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^#[multilib]", line: "[multilib]" }
        - { regexp: "^#Include = /etc/pacman.d/mirrorlist", line: "Include = /etc/pacman.d/mirrorlist"}
      notify:
        - Update Pacman cache

    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - base-devel
          - discord
          - code
          - haruna
          - libreoffice-still
          - libreoffice-still-es
          - timeshift
          - git
          - python-pip
          - python-virtualenv
          - keepassxc
          - kdeconnect
          - syncthing
          - obsidian
          - steam
        state: present

    - name: Install aur packages
      become: true
      become_user: "{{ arch_config_ansible_aur_user }}"
      vars:
        ansible_python_interpreter: /usr/bin/python
      kewlfft.aur.aur:
        name:
          - zen-browser-bin
          - stremio
          - syncthingtray-qt6
        state: present

  handlers:
    - name: Update Pacman cache
      community.general.pacman:
        update_cache: true
