---
- name: Configure my PC
  hosts: localhost
  vars:
    arch_config_ansible_aur_user: aur_builder
    arch_config_install_timeshift: true
  roles:
    - arch_config
  tasks:
    - name: Enable multilib
      become: true
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: "^#\\[multilib\\]\n#Include = /etc/pacman.d/mirrorlist$"
        replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
      notify: Update Pacman cache

    - name: Force handlers execution
      ansible.builtin.meta: flush_handlers

    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - base-devel
          - discord
          - code
          - qt6-multimedia-ffmpeg
          - haruna
          - libreoffice-fresh
          - libreoffice-fresh-es
          - timeshift
          - git
          - python-pip
          - python-virtualenv
          - keepassxc
          - kdeconnect
          - syncthing
          - obsidian
        state: present

    - name: Install aur packages
      become: true
      become_user: "{{ arch_config_ansible_aur_user }}"
      vars:
        ansible_python_interpreter: /usr/bin/python
      kewlfft.aur.aur:
        name:
          - zen-browser-bin
          - stremio
          - syncthingtray-qt6
        state: present

  handlers:
    - name: Update Pacman cache
      become: true
      community.general.pacman:
        update_cache: true
