---
- name: configure_pacman | Enable color
  become: true
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#Color'
    replace: 'Color'

- name: configure_pacman | Create hooks directory
  become: true
  ansible.builtin.file:
    name: /etc/pacman.d/hooks
    state: directory
    mode: '0644'

- name: configure_pacman | Clean cache when doing pacman update
  become: true
  ansible.builtin.copy:
    src: files/clean_cache.hook
    dest: /etc/pacman.d/hooks/clean_cache_paccache.hook
    mode: '0644'
