---
- name: configure_pacman | Create hooks directory
  become: true
  ansible.builtin.file:
    name: /etc/pacman.d/hooks
    state: directory
    mode: '0644'

- name: configure_pacman | Clean cache when doing pacman update
  become: true
  ansible.builtin.copy:
    src: files/clean_cache.hook
    dest: /etc/pacman.d/hooks/clean_cache.hook
    mode: '0644'
