---
- name: install_packages | Install pacman packages
  become: true
  community.general.pacman:
    name:
      - base-devel
      - discord
      - code
      - qt6-multimedia-ffmpeg
      - haruna
      - libreoffice-fresh
      - libreoffice-fresh-es
      - hunspell-es_ar
      - timeshift
      - git
      - python-pip
      - python-virtualenv
      - keepassxc
      - syncthing
      - obsidian
    state: present

- name: install_packages | Install aur packages
  become: true
  become_user: "{{ arch_config_ansible_aur_user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python
  kewlfft.aur.aur:
    name:
      - paru
      - zen-browser-bin
      - stremio
      - syncthingtray-qt6
    state: present
