---
- name: Install collection kewlfft.aur
  community.general.ansible_galaxy_install:
    type: collection
    name: kewlfft.aur

- name: GCC build optimizations
  ansible.builtin.import_tasks: makepkg_config.yml

- name: Configure pacman
  tags: pacman
  become: true
  ansible.builtin.import_tasks: pacman_config.yml

- name: Configure aur
  tags: aur
  ansible.builtin.include_tasks: aur_config.yml

- name: Install packages
  tags: install_packages
  ansible.builtin.include_tasks: install_packages.yml

- name: Configure Zram
  tags: zram
  ansible.builtin.import_tasks: zram_config.yml

- name: Configure timeshift
  tags: timeshift
  ansible.builtin.import_tasks: timeshift_config.yml
  when: arch_config_install_timeshift

- name: Create vi symlink
  become: true
  ansible.builtin.file:
    src: /usr/bin/vim
    dest: /usr/bin/vi
    state: link

- name: Create ntsync module file
  become: true
  ansible.builtin.copy:
    dest: "/etc/modules-load.d/ntsync.conf"
    mode: "0644"
    content: ntsync
