---
- name: pacman_config | Install required pacman-contrib y reflector
  ansible.builtin.package:
    name:
      - pacman-contrib
      - reflector
    state: present

- name: pacman_config | Enable color
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: "^#Color"
    replace: "Color"

- name: pacman_config | Enable multilib
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: "^#\\[multilib\\]\n#Include = /etc/pacman.d/mirrorlist$"
    replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
  notify: Update Pacman cache

- name: pacman_config | Create hooks directory
  ansible.builtin.file:
    name: /etc/pacman.d/hooks
    state: directory
    mode: "0644"

- name: pacman_config | Clean cache when doing pacman update
  ansible.builtin.copy:
    src: files/clean_cache.hook
    dest: /etc/pacman.d/hooks/clean_cache_paccache.hook
    mode: "0644"

- name: pacman_config | Configure reflector.conf
  ansible.builtin.template:
    src: reflector.conf.j2
    dest: /etc/xdg/reflector/reflector.conf
    mode: "0644"
  notify:
    - Enable reflector
